// site/components/Alert.jsx
import React from 'react'

export default function Alert () {
  return (
    <div className="container mx-auto mt-12">

      <h1>Alerts</h1>

      <p className="py-4">
        Elements that contain a message designed to give users context around
        something that has recently happened. These messages should draw more
        attention than standard text.
      </p>

      <div className="flex py-4 flex-wrap">

        <div className="example mr-8 mt-8 mb-8">

          <div className="alert alert-info">
            <strong>Hey hey!</strong> Here is some info to read.
          </div>

        </div>

        <div className="example mr-8 mt-8 mb-8">

          <div className="alert alert-success">
            <strong>Success!</strong> You have seen this alert.
          </div>

        </div>

        <div className="example mr-8 mt-8 mb-8">

          <div className="alert alert-warning">
            <strong>Warning!</strong> You are reading an alert.
          </div>

        </div>

        <div className="example mr-8 mt-8 mb-8">

          <div className="alert alert-danger">
            <strong>Error!</strong> Something is not quite right.
          </div>

        </div>

      </div>

    </div>
  )
}

// site/components/Alert.svelte
<script>
  import * as eva from 'eva-icons'
  import { onMount } from 'svelte'

  onMount(() => eva.replace())
</script>

<a href="#alert">
  <h1 class="text-4xl font-semibold">Alert</h1>
</a>

<p class="text-lg py-2">
  An element that contains a message designed to give users context around
  something that has recently happened. These messages should draw more
  attention than standard text.
</p>

<div class="pt-8 pb-4">

  <div class="alert alert-info">

    <i
      data-eva="info"
      data-eva-height="32"
      data-eva-width="32"
      class="float-left mr-3 fill-current"
    />

    <strong>Hey hey!</strong> Here is some info to read.

    <i
      data-eva="close"
      data-eva-height="32"
      data-eva-width="32"
      class="float-right fill-current cursor-pointer"
    />

  </div>

  <div class="alert alert-success mt-8">

    <i
      data-eva="checkmark-circle-2"
      data-eva-height="32"
      data-eva-width="32"
      class="float-left mr-3 fill-current"
    />

    <strong>Success!</strong> You have seen this alert.

    <i
      data-eva="close"
      data-eva-height="32"
      data-eva-width="32"
      class="float-right fill-current cursor-pointer"
    />

  </div>

  <div class="alert alert-warning mt-8">

    <i
      data-eva="alert-triangle"
      data-eva-height="32"
      data-eva-width="32"
      class="float-left mr-3 fill-current"
    />

    <strong>Warning!</strong> You are reading an alert.

    <i
      data-eva="close"
      data-eva-height="32"
      data-eva-width="32"
      class="float-right fill-current cursor-pointer"
    />

  </div>

  <div class="alert alert-danger mt-8">

    <i
      data-eva="close-circle"
      data-eva-height="32"
      data-eva-width="32"
      class="float-left mr-3 fill-current"
    />

    <strong>Error!</strong> Something happened. And it's not great.

    <i
      data-eva="close"
      data-eva-height="32"
      data-eva-width="32"
      class="float-right fill-current cursor-pointer"
    />

  </div>

</div>
