// site/components/Button.svelte
<script>
  import * as eva from 'eva-icons'
  import { onMount } from 'svelte'

  let preventDefault = e => e.preventDefault()

  onMount(() => eva.replace())
</script>

<div class="container w-auto mx-5 sm:mx-auto mt-5">

  <h1 class="text-4xl font-semibold">Button</h1>

  <p class="text-lg">
    An element that users click or touch to perform an action.
  </p>

  <div class="pt-10 flex items-center">

    <a href="/" on:click={preventDefault} class="button button-blue mr-4">
      Login
    </a>

    <a href="/" on:click={preventDefault} class="button button-blue flex items-center">
      <i data-eva="plus-circle" class="fill-current mr-1"></i> Add User
    </a>

  </div>

</div>

// site/components/Button.jsx
import React from 'react'

export default function Button () {
  return (
    <div className="container mx-auto mt-12">

      <h1>Buttons</h1>

      <p className="py-4 text-lg">
        Elements that users click or touch to perform an action.
      </p>

      <div className="flex flex-wrap justify-around py-4">

        <div className="example my-8">

          <a
            href="#"
            className="btn btn-blue"
          >
            Anchor btn-indigo
          </a>

        </div>

        <div className="example my-8">

          <button
            className="btn btn-indigo"
          >
            Button btn-indigo
          </button>

        </div>

        <div className="example my-8">

          <button
            className="btn btn-white"
          >
            Button btn-white
          </button>

        </div>

      </div>

    </div>
  )
}
